-- Peekr Seed Data
-- Demo shops and ads for testing and development

-- ============================================================================
-- DEMO SHOPS DATA (12 existing shops)
-- ============================================================================

INSERT INTO shops (
  name, domain, niche, score, trend_tag, country, created_date,
  monthly_visits, revenue_min, revenue_max, live_ads, theme, currency,
  products_count, language, shopify_plan, apps, ad_platforms, strategies,
  visitor_countries, traffic_trend
) VALUES
  (
    'Bezel',
    'bezel.com',
    'Mobile Accessories',
    87,
    'hot',
    'US',
    '2021-03-15',
    1240000,
    850000,
    1200000,
    42,
    'debut',
    'USD',
    350,
    'en',
    'Advanced',
    ARRAY['Omnisend', 'Recharge', 'PageFly', 'Growave'],
    ARRAY['Meta', 'TikTok', 'Google', 'Pinterest'],
    ARRAY['Seasonal campaigns', 'UGC content', 'Bundle upsell'],
    ARRAY['US', 'CA', 'AU', 'UK', 'DE'],
    ARRAY[980, 1020, 1050, 1120, 1180, 1240, 1280, 1310, 1340, 1380, 1420, 1450]
  ),
  (
    'Lively',
    'livelywear.com',
    'Fashion & Apparel',
    84,
    'hot',
    'US',
    '2020-08-22',
    980000,
    720000,
    950000,
    38,
    'narrative',
    'USD',
    420,
    'en',
    'Advanced',
    ARRAY['Gorgias', 'Judge.me', 'Smile', 'Yotpo'],
    ARRAY['Meta', 'Instagram', 'TikTok'],
    ARRAY['Influencer collab', 'Product education', 'Community building'],
    ARRAY['US', 'CA', 'AU', 'UK'],
    ARRAY[750, 790, 820, 880, 920, 960, 990, 1010, 1020, 1040, 1080, 1120]
  ),
  (
    'Skims',
    'skims.com',
    'Fashion & Apparel',
    92,
    'hot',
    'US',
    '2019-06-10',
    3500000,
    4200000,
    6500000,
    67,
    'custom',
    'USD',
    580,
    'en',
    'Plus',
    ARRAY['Gorgias', 'Privy', 'Yotpo', 'Subbly', 'Triple Whale'],
    ARRAY['Meta', 'Google', 'TikTok', 'Pinterest'],
    ARRAY['Celebrity endorsement', 'Size inclusivity', 'Video content'],
    ARRAY['US', 'CA', 'UK', 'AU', 'DE', 'FR'],
    ARRAY[3200, 3350, 3480, 3620, 3750, 3890, 4020, 4150, 4280, 4420, 4580, 4720]
  ),
  (
    'Outdoor Voices',
    'outdoorvoices.com',
    'Fitness & Sports',
    76,
    'rising',
    'US',
    '2018-11-05',
    580000,
    420000,
    680000,
    28,
    'prestige',
    'USD',
    290,
    'en',
    'Plus',
    ARRAY['Gorgias', 'LoyaltyLion', 'Reflex'],
    ARRAY['Meta', 'Instagram', 'YouTube'],
    ARRAY['Athlete partnerships', 'Community events', 'Sustainability focus'],
    ARRAY['US', 'CA', 'UK'],
    ARRAY[450, 485, 510, 545, 580, 610, 645, 675, 710, 750, 785, 820]
  ),
  (
    'Grace Loves Lace',
    'graceloveslace.com',
    'Wedding & Special Events',
    82,
    'hot',
    'AU',
    '2017-02-14',
    720000,
    550000,
    890000,
    35,
    'brooklyn',
    'AUD',
    240,
    'en',
    'Plus',
    ARRAY['Klaviyo', 'Judge.me', 'Littledata', 'Mimecast'],
    ARRAY['Meta', 'Pinterest', 'Instagram'],
    ARRAY['Pinterest SEO', 'Email nurture', 'Influencer gifting'],
    ARRAY['AU', 'US', 'UK', 'NZ', 'CA'],
    ARRAY[550, 580, 610, 650, 690, 720, 750, 780, 810, 850, 890, 920]
  ),
  (
    'Allbirds',
    'allbirds.com',
    'Footwear & Accessories',
    88,
    'hot',
    'US',
    '2016-03-28',
    1850000,
    1400000,
    1900000,
    52,
    'debut',
    'USD',
    125,
    'en',
    'Plus',
    ARRAY['Gorgias', 'Sweettooth', 'Judge.me', 'Littledata'],
    ARRAY['Meta', 'Google', 'YouTube', 'Pinterest'],
    ARRAY['Sustainability messaging', 'Community engagement', 'UGC'],
    ARRAY['US', 'CA', 'AU', 'UK', 'DE', 'FR', 'JP'],
    ARRAY[1400, 1480, 1560, 1650, 1740, 1820, 1900, 1960, 2010, 2080, 2150, 2220]
  ),
  (
    'Glossier',
    'glossier.com',
    'Beauty & Cosmetics',
    91,
    'hot',
    'US',
    '2014-10-19',
    2100000,
    1800000,
    2400000,
    58,
    'custom',
    'USD',
    280,
    'en',
    'Plus',
    ARRAY['Gorgias', 'Yotpo', 'Recharge', 'Shoelace'],
    ARRAY['Meta', 'Instagram', 'YouTube', 'TikTok'],
    ARRAY['TikTok influencer', 'User-generated content', 'Community'],
    ARRAY['US', 'CA', 'UK', 'AU', 'DE', 'FR'],
    ARRAY[1700, 1810, 1920, 2040, 2150, 2280, 2380, 2450, 2530, 2620, 2710, 2800]
  ),
  (
    'Fashion Nova',
    'fashionnova.com',
    'Fashion & Apparel',
    79,
    'rising',
    'US',
    '2013-06-01',
    2450000,
    2100000,
    3200000,
    64,
    'supply',
    'USD',
    820,
    'en',
    'Plus',
    ARRAY['Gorgias', 'Judge.me', 'Reamaze', 'Zipify'],
    ARRAY['Meta', 'Instagram', 'TikTok', 'YouTube'],
    ARRAY['Influencer marketing', 'Flash sales', 'New drops strategy'],
    ARRAY['US', 'CA', 'UK', 'AU'],
    ARRAY[1950, 2050, 2150, 2280, 2380, 2450, 2520, 2580, 2650, 2750, 2880, 3020]
  ),
  (
    'Gymshark',
    'gymshark.com',
    'Fitness & Sports',
    85,
    'hot',
    'UK',
    '2012-09-03',
    1680000,
    1200000,
    1650000,
    46,
    'narrative',
    'GBP',
    310,
    'en',
    'Plus',
    ARRAY['Gorgias', 'Yotpo', 'Recharge', 'Judge.me'],
    ARRAY['Meta', 'YouTube', 'TikTok', 'Instagram'],
    ARRAY['Creator partnerships', 'Product launches', 'Community engagement'],
    ARRAY['UK', 'US', 'AU', 'CA', 'DE'],
    ARRAY[1200, 1320, 1420, 1540, 1650, 1750, 1840, 1920, 2010, 2100, 2210, 2340]
  ),
  (
    'Savage X Fenty',
    'savagex.com',
    'Fashion & Apparel',
    90,
    'hot',
    'US',
    '2018-05-11',
    2850000,
    2500000,
    3800000,
    71,
    'custom',
    'USD',
    350,
    'en',
    'Plus',
    ARRAY['Gorgias', 'Yotpo', 'Recharge', 'Privy', 'Judge.me'],
    ARRAY['Meta', 'Instagram', 'YouTube', 'TikTok'],
    ARRAY['Celebrity brand', 'Diversity focus', 'Bold marketing'],
    ARRAY['US', 'CA', 'UK', 'AU', 'DE', 'FR'],
    ARRAY[2300, 2480, 2640, 2820, 3010, 3200, 3380, 3560, 3720, 3890, 4080, 4250]
  ),
  (
    'Rothy''s',
    'rothys.com',
    'Footwear & Accessories',
    83,
    'rising',
    'US',
    '2016-01-20',
    920000,
    620000,
    950000,
    41,
    'debut',
    'USD',
    185,
    'en',
    'Plus',
    ARRAY['Gorgias', 'Judge.me', 'Littledata', 'Sweettooth'],
    ARRAY['Meta', 'Instagram', 'Pinterest', 'Google'],
    ARRAY['Sustainability', 'Recycled materials', 'Quality messaging'],
    ARRAY['US', 'CA', 'AU', 'UK'],
    ARRAY[680, 740, 780, 840, 890, 950, 990, 1020, 1080, 1150, 1220, 1290]
  ),
  (
    'Sheglam',
    'sheglam.com',
    'Beauty & Cosmetics',
    78,
    'watch',
    'US',
    '2018-03-08',
    1560000,
    950000,
    1450000,
    39,
    'supply',
    'USD',
    420,
    'en',
    'Plus',
    ARRAY['Gorgias', 'Yotpo', 'Privy', 'Judge.me'],
    ARRAY['Meta', 'TikTok', 'Instagram', 'YouTube'],
    ARRAY['TikTok viral trends', 'Affordable luxury', 'Collaborations'],
    ARRAY['US', 'CA', 'UK', 'AU'],
    ARRAY[1150, 1280, 1380, 1520, 1650, 1750, 1880, 1980, 2100, 2250, 2380, 2520]
  );

-- ============================================================================
-- DEMO ADS DATA (16 trending ads)
-- ============================================================================

-- Get the shop IDs we just inserted for linking ads
WITH inserted_shops AS (
  SELECT id, name FROM shops WHERE domain IN (
    'bezel.com', 'livelywear.com', 'skims.com', 'outdoorvoices.com',
    'graceloveslace.com', 'allbirds.com', 'glossier.com', 'fashionnova.com'
  )
)
INSERT INTO ads (
  shop_id, platform, format, headline, copy, status, days_active, likes, shares, creative_url
) VALUES
  (
    (SELECT id FROM inserted_shops WHERE name = 'Bezel'),
    'meta',
    'video',
    'Protect Your iPhone in Style',
    'Premium protection meets minimalist design. Bezel cases keep your phone safe without the bulk. Free shipping on all orders.',
    'active',
    47,
    12400,
    850,
    'https://adlibrary-media.facebook.com/bezel-iphone-case-001.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Bezel'),
    'tiktok',
    'video',
    'Drop-tested. Drop-approved.',
    'POV: Your phone survives the worst. #PhoneProtection #BezelCases',
    'active',
    34,
    28500,
    2140,
    'https://video.tiktok.com/bezel-drop-test.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Lively'),
    'meta',
    'carousel',
    'Feel the Difference',
    'Comfort engineered. Designed for your body. Shop our bestselling collection now.',
    'active',
    52,
    8900,
    620,
    'https://adlibrary-media.facebook.com/lively-carousel-001.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Lively'),
    'pinterest',
    'image',
    'Comfort is Key',
    'Discover the basics that actually feel amazing. Save for later inspiration.',
    'active',
    89,
    15600,
    3200,
    'https://cdn.pinterest.com/lively-comfort-pins.jpg'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Skims'),
    'meta',
    'video',
    'Solutions for Every Body',
    'Shape, smooth, and support. SKIMS works with your body. Get the smoothest look under any outfit.',
    'active',
    128,
    45800,
    5200,
    'https://adlibrary-media.facebook.com/skims-solutions-001.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Skims'),
    'instagram',
    'image',
    'Seamless Innovation',
    'Shop our bestselling styles. Link in bio.',
    'active',
    156,
    62300,
    7890,
    'https://instagram.com/skims/p/000001.jpg'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Outdoor Voices'),
    'meta',
    'video',
    'Do the Thing',
    'Get outside. Get moving. Get OV. New season gear is here.',
    'active',
    41,
    6200,
    380,
    'https://adlibrary-media.facebook.com/ov-do-the-thing.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Outdoor Voices'),
    'youtube',
    'video',
    'Made to Move',
    'Performance gear that looks good off the trail too. Functional fashion.',
    'active',
    67,
    4100,
    190,
    'https://youtube.com/outdoorvoices/do-the-thing.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Grace Loves Lace'),
    'pinterest',
    'image',
    'Your Fairytale Awaits',
    'Explore our bridal collection. Wedding dresses for every vision.',
    'active',
    203,
    28900,
    4500,
    'https://cdn.pinterest.com/grace-loves-lace-bridal.jpg'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Grace Loves Lace'),
    'meta',
    'carousel',
    'Say Yes to the Dress',
    'Featuring our new collection. Custom fittings available. Book now.',
    'active',
    98,
    11200,
    1340,
    'https://adlibrary-media.facebook.com/grace-carousel-bridal.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Allbirds'),
    'meta',
    'video',
    'Comfort Built In',
    'Our softest, most sustainable sneakers yet. Designed for comfort, made for the planet.',
    'active',
    73,
    18600,
    2100,
    'https://adlibrary-media.facebook.com/allbirds-comfort.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Allbirds'),
    'google',
    'image',
    'Step Into Comfort',
    'Shop Allbirds sustainable sneakers. Free returns & exchanges.',
    'active',
    112,
    9800,
    650,
    'https://ads.google.com/allbirds-sneakers.jpg'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Glossier'),
    'tiktok',
    'video',
    'Skin first. Beauty second.',
    'The only products you actually need. Glossier Essentials. #GlossierGirl',
    'active',
    156,
    89200,
    12400,
    'https://video.tiktok.com/glossier-skin-first.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Glossier'),
    'instagram',
    'carousel',
    'Glow Without the Guilt',
    'Clean beauty that actually works. Save 20% on your first order.',
    'active',
    198,
    156700,
    18900,
    'https://instagram.com/glossier/p/carousel-001.jpg'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Fashion Nova'),
    'tiktok',
    'video',
    'New Drop Alert',
    'The hottest styles just dropped. Shop now before they''re gone. #FashionNova #LVOE',
    'active',
    31,
    134500,
    28900,
    'https://video.tiktok.com/fashionnova-new-drop.mp4'
  ),
  (
    (SELECT id FROM inserted_shops WHERE name = 'Fashion Nova'),
    'meta',
    'video',
    'Trendsetter Alert',
    'Exclusive styles. Limited quantities. Shop the latest collection. Free shipping over $50.',
    'active',
    47,
    92100,
    11200,
    'https://adlibrary-media.facebook.com/fashionnova-trends.mp4'
  );

-- ============================================================================
-- INDEX REFRESH (if using materialized views)
-- ============================================================================
-- Uncomment if materialized views were created:
-- REFRESH MATERIALIZED VIEW CONCURRENTLY top_shops_by_score;
-- REFRESH MATERIALIZED VIEW CONCURRENTLY trending_niches_summary;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Run these to verify the seed data was inserted correctly:

-- SELECT COUNT(*) as total_shops FROM shops;
-- SELECT COUNT(*) as total_ads FROM ads;
-- SELECT domain, live_ads FROM shops ORDER BY live_ads DESC LIMIT 5;
-- SELECT name, platform, status, likes FROM ads ORDER BY likes DESC LIMIT 5;
